// components/nodes/VNode.vue
<template>
  <div class="flex py-0.5">
    <!-- <div v-if="node != null">{{ node.constructor }}</div> -->
    <div v-if="node == null" class="w-full">
      <v-null
        :field="field"
        :value="node"
        :showEndComma="showEndComma"
      ></v-null>
    </div>
    <div v-else-if="node.constructor === Object" class="w-full">
      <v-object
        :field="field"
        :object="node"
        :showEndComma="showEndComma"
      ></v-object>
    </div>
    <div v-else-if="node.constructor === Array" class="w-full">
      <v-array
        :field="field"
        :array="node"
        :showEndComma="showEndComma"
      ></v-array>
    </div>
    <div v-else-if="node.constructor === String" class="w-full">
      <v-string
        :field="field"
        :value="node"
        :showEndComma="showEndComma"
      ></v-string>
    </div>
    <div v-else-if="node.constructor === Number" class="w-full">
      <v-number
        :field="field"
        :value="node"
        :showEndComma="showEndComma"
      ></v-number>
    </div>
    <div v-else-if="node.constructor === Boolean" class="w-full">
      <v-boolean
        :field="field"
        :value="node"
        :showEndComma="showEndComma"
      ></v-boolean>
    </div>
  </div>
</template>


<script lang="ts">
import { defineComponent } from "@nuxtjs/composition-api";

export default defineComponent({
  name: "VNode",
  props: {
    field: {
      type: [String, Number],
      required: false,
    },
    node: {
      type: [Object, Array, Number, String, Boolean],
    },
    showEndComma: {
      type: [Boolean],
      default: true,
    },
  },
});
</script>

// components/nodes/VNode.tsx
import VNull from './VNull'
import VObject from './VObject'
import VArray from './VArray'
import VString from './VString'
import VNumber from './VNumber'
import VBoolean from './VBoolean'

interface VNodeProps {
  field?: string | number
  node: any
  showEndComma?: boolean
  className?: string
}

export default function VNode({ field, node, showEndComma = true, className = '' }: VNodeProps) {
  const renderNode = () => {
    if (node == null) {
      return <VNull field={field} value={node} showEndComma={showEndComma} />
    } else if (typeof node === 'object' && !Array.isArray(node)) {
      return <VObject field={field} object={node} showEndComma={showEndComma} />
    } else if (Array.isArray(node)) {
      return <VArray field={field} array={node} showEndComma={showEndComma} />
    } else if (typeof node === 'string') {
      return <VString field={field} value={node} showEndComma={showEndComma} />
    } else if (typeof node === 'number') {
      return <VNumber field={field} value={node} showEndComma={showEndComma} />
    } else if (typeof node === 'boolean') {
      return <VBoolean field={field} value={node} showEndComma={showEndComma} />
    }
    return null
  }

  return (
    <div className={`flex py-0.5 ${className}`}>
      <div className="w-full">{renderNode()}</div>
    </div>
  )
}
