// components/nodes/VString.tsx
import Field from './Field'

interface VStringProps {
  field?: string | number
  value: string
  showEndComma?: boolean
}

export default function VString({ field, value, showEndComma = true }: VStringProps) {
  return (
    <div className="flex">
      {field && (
        <>
          <Field field={field} />
          <p className="pr-1">:</p>
        </>
      )}
      <p style={{ color: '#d98e73', maxWidth: '40vw' }} className="break-words">
        &quot;{value}&quot;{showEndComma && <span style={{ color: '#d4d4d4' }}>,</span>}
      </p>
    </div>
  )
}

// components/nodes/VString.vue
<template>
  <div class="flex">
    <template v-if="field">
      <field :field="field"></field>
      <p class="pr-1">:</p>
    </template>
    <p style="color: #d98e73; max-width: 40vw" class="break-words">
      "{{ value }}"<span v-if="showEndComma" style="color: #d4d4d4">,</span>
    </p>
  </div>
</template>


<script lang="ts">
import { defineComponent } from "@nuxtjs/composition-api";

export default defineComponent({
  name: "VString",
  props: {
    field: {
      type: [String],
    },
    value: {
      type: [String],
      required: true,
    },
    showEndComma: {
      type: [Boolean],
      default: true,
    },
  },
});
</script>
