// components/nodes/VNumber.tsx
import Field from './Field'

interface VNumberProps {
  field?: string | number
  value: number
  showEndComma?: boolean
}

export default function VNumber({ field, value, showEndComma = true }: VNumberProps) {
  return (
    <div className="flex">
      {field && (
        <>
          <Field field={field} />
          <p className="pr-1">:</p>
        </>
      )}
      <p style={{ color: '#afcfa4' }}>
        {value}{showEndComma && <span style={{ color: '#d4d4d4' }}>,</span>}
      </p>
    </div>
  )
}

// components/VNumber.vue
<template>
  <div class="flex">
    <template v-if="field">
      "{{ field }}"
      <p class="pr-1">:</p>
    </template>
    <p>{{ value }}<span v-if="showEndComma">,</span></p>
  </div>
</template>


<script lang="ts">
import { defineComponent } from "@nuxtjs/composition-api";

export default defineComponent({
  name: "VNumber",
  props: {
    field: {
      type: [String],
      required: false,
    },
    value: {
      type: [Number],
      required: true,
    },
    showEndComma: {
      type: [Boolean],
      default: true,
    },
  },
});
</script>
